baseURL = 'https://liveclock.ngs.io/'
title = 'LiveClock'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
contentDir = "content/en"
languageCode = "en"
languageName = "English"
weight = 1
[languages.ar]
contentDir = "content/ar"
languageCode = "ar"
languageDirection = "rtl"
languageName = "العربية"
weight = 2
[languages.ca]
contentDir = "content/ca"
languageCode = "ca"
languageName = "Català"
weight = 3
[languages.cs]
contentDir = "content/cs"
languageCode = "cs"
languageName = "Čeština"
weight = 4
[languages.da]
contentDir = "content/da"
languageCode = "da"
languageName = "Dansk"
weight = 5
[languages.de]
contentDir = "content/de"
languageCode = "de"
languageName = "Deutsch"
weight = 6
[languages.el]
contentDir = "content/el"
languageCode = "el"
languageName = "Ελληνικά"
weight = 7
[languages.es]
contentDir = "content/es"
languageCode = "es"
languageName = "Español"
weight = 8
[languages.fi]
contentDir = "content/fi"
languageCode = "fi"
languageName = "Suomi"
weight = 9
[languages.fr]
contentDir = "content/fr"
languageCode = "fr"
languageName = "Français"
weight = 10
[languages.he]
contentDir = "content/he"
languageCode = "he"
languageDirection = "rtl"
languageName = "עברית"
weight = 11
[languages.hi]
contentDir = "content/hi"
languageCode = "hi"
languageName = "हिन्दी"
weight = 12
[languages.hr]
contentDir = "content/hr"
languageCode = "hr"
languageName = "Hrvatski"
weight = 13
[languages.hu]
contentDir = "content/hu"
languageCode = "hu"
languageName = "Magyar"
weight = 14
[languages.id]
contentDir = "content/id"
languageCode = "id"
languageName = "Bahasa Indonesia"
weight = 15
[languages.it]
contentDir = "content/it"
languageCode = "it"
languageName = "Italiano"
weight = 16
[languages.ja]
contentDir = "content/ja"
languageCode = "ja"
languageName = "日本語"
weight = 17
[languages.ko]
contentDir = "content/ko"
languageCode = "ko"
languageName = "한국어"
weight = 18
[languages.ms]
contentDir = "content/ms"
languageCode = "ms"
languageName = "Bahasa Melayu"
weight = 19
[languages.nl]
contentDir = "content/nl"
languageCode = "nl"
languageName = "Nederlands"
weight = 20
[languages.no]
contentDir = "content/no"
languageCode = "no"
languageName = "Norsk"
weight = 21
[languages.pl]
contentDir = "content/pl"
languageCode = "pl"
languageName = "Polski"
weight = 22
[languages.pt-br]
contentDir = "content/pt-br"
languageCode = "pt-BR"
languageName = "Português (Brasil)"
weight = 23
[languages.pt-pt]
contentDir = "content/pt-pt"
languageCode = "pt-PT"
languageName = "Português (Portugal)"
weight = 24
[languages.ro]
contentDir = "content/ro"
languageCode = "ro"
languageName = "Română"
weight = 25
[languages.ru]
contentDir = "content/ru"
languageCode = "ru"
languageName = "Русский"
weight = 26
[languages.sk]
contentDir = "content/sk"
languageCode = "sk"
languageName = "Slovenčina"
weight = 27
[languages.sv]
contentDir = "content/sv"
languageCode = "sv"
languageName = "Svenska"
weight = 28
[languages.th]
contentDir = "content/th"
languageCode = "th"
languageName = "ไทย"
weight = 29
[languages.tr]
contentDir = "content/tr"
languageCode = "tr"
languageName = "Türkçe"
weight = 30
[languages.uk]
contentDir = "content/uk"
languageCode = "uk"
languageName = "Українська"
weight = 31
[languages.vi]
contentDir = "content/vi"
languageCode = "vi"
languageName = "Tiếng Việt"
weight = 32
[languages.zh-hans]
contentDir = "content/zh-hans"
languageCode = "zh-hans"
languageName = "简体中文"
weight = 33
[languages.zh-hant]
contentDir = "content/zh-hant"
languageCode = "zh-hant"
languageName = "繁體中文"
weight = 34

[permalinks]
[permalinks.page]
privacy = "/privacy/"
